version: '3.8'
services:
  analytics_web:
    restart: on-failure
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/service
    ports:
      - "8004:8000"
    depends_on:
      analytics_db:
        condition: service_healthy

  analytics_db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_user_password
      POSTGRES_DB: analytics_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5

  analytics_celery:
    restart: on-failure
    build: .
    command: bash -c "celery -A analytics_service worker --loglevel=INFO"
    environment:
      - DJANGO_SETTINGS_MODULE=analytics_service.settings
    volumes:
      - .:/service
    depends_on:
      analytics_rabbitmq:
        condition: service_healthy
      analytics_db:
        condition: service_healthy

  analytics_celery_beat:
    restart: on-failure
    build: .
    command: celery -A analytics_service worker -B --loglevel=INFO
    environment:
      - DJANGO_SETTINGS_MODULE=analytics_service.settings
    volumes:
      - .:/service
    depends_on:
      analytics_rabbitmq:
        condition: service_healthy
      analytics_db:
        condition: service_healthy

  analytics_consumer:
    build: .
    restart: on-failure
    command: python manage.py runconsumer
    volumes:
      - .:/service
    depends_on:
      analytics_db:
        condition: service_healthy

  analytics_rabbitmq:
    restart: on-failure
    image: rabbitmq:management
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
      name: popug-network
      external: true
