version: '3.8'
services:
  auth:
    restart: on-failure
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/service
    ports:
      - "8001:8000"
    depends_on:
      auth_db:
        condition: service_healthy

  auth_db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_user_password
      POSTGRES_DB: auth_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 1s
      timeout: 5s
      retries: 10
networks:
  default:
      name: popug-network
      external: true
