version: '3.8'
services:
  task_tracker_web:
    restart: on-failure
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/service
    ports:
      - "8002:8000"

  task_tracker_db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: task_tracker_user
      POSTGRES_PASSWORD: task_tracker_user_password
      POSTGRES_DB: task_tracker_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 1s
      timeout: 5s
      retries: 10

  task_tracker_celery:
    restart: on-failure
    build: .
    command: bash -c "celery -A task_service worker --loglevel=INFO"
    environment:
      - DJANGO_SETTINGS_MODULE=task_service.settings
    volumes:
      - .:/service
    depends_on:
      task_tracker_rabbitmq:
        condition: service_healthy

  task_tracker_consumer:
    build: .
    restart: on-failure
    command: python manage.py runconsumer
    volumes:
      - .:/service

  task_tracker_rabbitmq:
    restart: on-failure
    image: rabbitmq:management
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  default:
      name: popug-network
      external: true
